import { Inter } from 'next/font/google'
import './globals.css'
import { CartContext, CartProvider } from './components/CartContext'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Codeswear.com',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <CartProvider>

    <html lang="en">
      <body classnameName={inter.classnameName}>{children}</body>
    </html>
    </CartProvider>

  )
}
